"""Algorithm-independent active inverse-optimization benchmark environments."""

from .algorithms import (
    ActiveAlgorithm,
    CallbackActiveAlgorithm,
    RandomActiveAlgorithm,
    UniformRandomIncenterAlgorithm,
    create_uniform_random_incenter_algorithm,
)
from .config import (
    ActiveBenchmarkGrid,
    ActiveScenarioConfig,
    DecisionSpaceConfig,
    DecisionSpaceKind,
    ExpertConfig,
    ExpertKind,
    ObservationNoiseConfig,
    ObservationNoiseKind,
    ParameterNoiseConfig,
    ParameterNoiseKind,
    QuerySpaceConfig,
    QuerySpaceKind,
)
from .decision_spaces import (
    ContinuousPolytopeDecisionSpace,
    DAGPathDecisionSpace,
    DecisionSpace,
    FixedCardinalityDecisionSpace,
    IndependentBinaryDecisionSpace,
    StructuredBinaryDecisionSpace,
    make_decision_space,
)
from .environment import ActiveInverseEnvironment
from .langevin import (
    GaussianSmoothedSampler,
    InverseLossTarget,
    NestedLangevinActiveAlgorithm,
    NestedLangevinConfig,
    create_nested_langevin_algorithm,
    disagreement_score,
)
from .evaluation import (
    ActiveEvaluationConfig,
    ActiveEvaluationResult,
    angular_error_degrees,
    evaluate_active_benchmark,
    evaluate_active_run,
    normalized_test_regret,
    sample_uniform_test_queries,
    sample_scenario_hidden_queries,
)
from .experts import Expert, GibbsExpert, MinExpert
from .sampling import GaussianGibbsSampler
from .query_designs import QueryDesign, build_query_sensitive_scenarios
from .comparison import (PedroAlgorithm, GeniousPedroAlgorithm, ScoreBaseAlgorithm, ComparisonDesign,
                         build_pedro_score_scenarios, run_pedro_score_design,
                         run_three_algorithm_design, run_four_algorithm_design)
from .samd import (
    OnlineSAMDConfig,
    UniformOnlineSAMDAlgorithm,
    create_uniform_online_samd_algorithm,
)
from .noise import ObservationNoise, ParameterNoise
from .query_spaces import QuerySpace, make_query_space
from .public import ConsistencyNormalBatch, PublicDecisionProblem
from .runner import (
    ActiveBenchmarkRunner,
    ActiveBenchmarkSuite,
    active_grid_from_dict,
    load_active_benchmark,
    load_algorithm_factory,
    load_active_scenarios,
)
from .stopping import RegretStoppingCheck, RegretStoppingConfig, RegretStoppingRule
from .research import (
    ActiveResearchConfig,
    build_active_research_scenarios,
    run_active_research_benchmark,
    save_active_research,
    summarize_active_research,
)
from .types import (
    ActiveAction,
    ActiveBenchmarkResult,
    ActiveRunResult,
    ActiveStepRecord,
    AlgorithmContext,
    AlgorithmObservation,
    EnvironmentFeedback,
)

__all__ = [
    "ActiveAction",
    "ActiveAlgorithm",
    "ActiveBenchmarkGrid",
    "ActiveBenchmarkResult",
    "ActiveBenchmarkRunner",
    "ActiveBenchmarkSuite",
    "ActiveInverseEnvironment",
    "ActiveEvaluationConfig",
    "ActiveEvaluationResult",
    "ActiveRunResult",
    "ActiveResearchConfig",
    "ActiveScenarioConfig",
    "ActiveStepRecord",
    "AlgorithmContext",
    "AlgorithmObservation",
    "CallbackActiveAlgorithm",
    "ContinuousPolytopeDecisionSpace",
    "ConsistencyNormalBatch",
    "DAGPathDecisionSpace",
    "DecisionSpace",
    "DecisionSpaceConfig",
    "DecisionSpaceKind",
    "EnvironmentFeedback",
    "Expert",
    "ExpertConfig",
    "ExpertKind",
    "FixedCardinalityDecisionSpace",
    "GibbsExpert",
    "IndependentBinaryDecisionSpace",
    "MinExpert",
    "GaussianSmoothedSampler",
    "GaussianGibbsSampler",
    "QueryDesign",
    "PedroAlgorithm",
    "GeniousPedroAlgorithm",
    "ScoreBaseAlgorithm",
    "UniformOnlineSAMDAlgorithm",
    "OnlineSAMDConfig",
    "ComparisonDesign",
    "build_pedro_score_scenarios",
    "run_pedro_score_design",
    "run_three_algorithm_design",
    "run_four_algorithm_design",
    "build_query_sensitive_scenarios",
    "InverseLossTarget",
    "NestedLangevinActiveAlgorithm",
    "NestedLangevinConfig",
    "create_nested_langevin_algorithm",
    "disagreement_score",
    "ObservationNoise",
    "ObservationNoiseConfig",
    "ObservationNoiseKind",
    "ParameterNoise",
    "ParameterNoiseConfig",
    "ParameterNoiseKind",
    "PublicDecisionProblem",
    "QuerySpace",
    "QuerySpaceConfig",
    "QuerySpaceKind",
    "RandomActiveAlgorithm",
    "RegretStoppingCheck",
    "RegretStoppingConfig",
    "RegretStoppingRule",
    "UniformRandomIncenterAlgorithm",
    "StructuredBinaryDecisionSpace",
    "load_active_scenarios",
    "load_active_benchmark",
    "load_algorithm_factory",
    "active_grid_from_dict",
    "angular_error_degrees",
    "create_uniform_random_incenter_algorithm",
    "create_uniform_online_samd_algorithm",
    "evaluate_active_benchmark",
    "evaluate_active_run",
    "make_decision_space",
    "make_query_space",
    "normalized_test_regret",
    "sample_uniform_test_queries",
    "sample_scenario_hidden_queries",
    "build_active_research_scenarios",
    "run_active_research_benchmark",
    "save_active_research",
    "summarize_active_research",
]
