from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

import numpy as np

from .core import ForwardProblem, InverseDataset
from .experiments import ExperimentResult, _jsonable
from .visualization import animate_cone_2d, plot_cone_3d, plot_loss_landscape_2d


def _table(mapping: dict[str, Any]) -> str:
    rows = []
    for key, value in mapping.items():
        if isinstance(value, float):
            displayed = f"{value:.6g}"
        else:
            displayed = str(value)
        rows.append(f"<tr><th>{html.escape(str(key))}</th><td>{html.escape(displayed)}</td></tr>")
    return "<table>" + "".join(rows) + "</table>"


def generate_html_report(
    result: ExperimentResult,
    problem: ForwardProblem,
    dataset: InverseDataset,
    destination: str | Path,
    *,
    loss: Any | None = None,
) -> Path:
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    interactive_sections: list[str] = []
    try:
        truth = next((obs.true_theta for obs in dataset if obs.true_theta is not None), None)
        if result.geometry_history and problem.parameter_space.dimension == 2:
            figure = animate_cone_2d(problem, result.geometry_history, true_theta=truth)
            interactive_sections.append("<h2>Cone evolution</h2>" + figure.to_html(full_html=False, include_plotlyjs="cdn"))
        elif result.geometry_history and problem.parameter_space.dimension == 3:
            figure = plot_cone_3d(problem, result.geometry_history[-1], true_theta=truth)
            interactive_sections.append("<h2>Final 3D consistency region</h2>" + figure.to_html(full_html=False, include_plotlyjs="cdn"))
        if loss is not None and problem.parameter_space.dimension == 2:
            # A moderate grid keeps reports responsive while still revealing the
            # piecewise structure of inverse losses.
            figure = plot_loss_landscape_2d(problem, dataset, loss, result=result, resolution=41)
            interactive_sections.append("<h2>Loss landscape</h2>" + figure.to_html(full_html=False, include_plotlyjs=False))
    except ImportError:
        interactive_sections.append("<p><em>Install invoptlab[plots] to include interactive figures.</em></p>")
    document = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(result.name)} - invoptlab report</title>
<style>
body {{font-family: Inter, Arial, sans-serif; max-width: 1200px; margin: 2rem auto; padding: 0 1rem; color: #202124;}}
h1,h2 {{color:#17324d}} table {{border-collapse:collapse; width:100%; margin-bottom:1.5rem}}
th,td {{border:1px solid #dfe3e8; padding:.5rem; text-align:left}} th {{background:#f5f7fa; width:42%}}
code {{background:#f5f7fa; padding:.1rem .25rem}} .grid {{display:grid; grid-template-columns:1fr 1fr; gap:1.5rem}}
@media(max-width:800px) {{.grid {{grid-template-columns:1fr}}}}
</style>
</head>
<body>
<h1>{html.escape(result.name)}</h1>
<p>Generated by <code>invoptlab</code>. Dataset fingerprint: <code>{html.escape(result.dataset_summary['fingerprint'])}</code>.</p>
<div class="grid"><section><h2>Estimated parameter</h2><pre>{html.escape(np.array2string(result.theta, precision=6))}</pre></section>
<section><h2>Run diagnostics</h2>{_table(result.diagnostics)}</section></div>
<h2>Metrics</h2>{_table(result.metrics)}
<h2>Dataset</h2>{_table(result.dataset_summary)}
{''.join(interactive_sections)}
<h2>Configuration</h2><pre>{html.escape(json.dumps(_jsonable(result.config), indent=2))}</pre>
</body></html>"""
    destination.write_text(document, encoding="utf-8")
    result.artifacts["html_report"] = str(destination)
    return destination
